### ISSUE TITLE
Addition- March4Justice

### ISSUE THREAD

**Issue by ash-burm** [mdavis-xyz/mdavis.xyz#8] opened 2021-03-16 05:43 UTC
Didn't shoot thousands of women marching to raise awareness of issues of sexual harassment and rape.

https://www.dailymail.co.uk/news/article-9362499/Scott-Morrison-slammed-saying-women-marching-countries-met-bullets.html

**Comment by mdavis-xyz** [comment] 2021-03-16 05:55
Everyone's talking about that comment, but the bigger story is that the soldiers in Myanmar who are shooting protestors were trained by Australia, even when they were known to be genocidal.

That's already in the list. 

In Australia, no one can criticism the lack of shooting itself. The problem is the comment and lack of response to the actual assault and culture problems. I deliberately haven't put *that* in the list yet, because that's quite hard to summarize succinctly, and everyone already knows about it. (Same reason I didn't put the carbon price removal in the list.)

**Comment by mdavis-xyz** [comment] 2021-03-25 09:12
Closing, as per my previous comment.

**Closed by mdavis-xyz** 2021-03-25 09:12 UTC
